Endpoint - Create User endpoint - GET
Ralexs0096/Tickets-API pull request #10
Opened 2023-10-16 20:56 UTC by leandro0day

We have created an endpoint for the url "/user" that, using the GET method, returns an array of objects with the first name, last name and area id of all the Users.

2023-10-16 23:28 UTC, Ralexs0096 commented on src/routes/users/fetchAllUsers.ts
> +  Reply: User[] | { error: { code: string; message: string } };
I think this is a good opportunity to use the errorSchema type

2023-10-16 23:28 UTC, Ralexs0096 commented on src/routes/users/fetchAllUsers.ts
> +        error: {
we can also use the error schema here

2023-10-16 23:28 UTC, Ralexs0096 commented on src/routes/users/fetchAllUsers.ts
> +        error: {
and here

2023-10-16 23:28 UTC, Ralexs0096 commented on src/routes/users/fetchAllUsers.ts
> +    200: {
if this returns an array of users, we can use the existing User interface on `/types` 😸

2023-10-16 23:28 UTC, Ralexs0096 commented on src/routes/users/fetchAllUsers.ts
> +    const users = await UserModel.query().select("firstName", "lastName","areaId");
in this case, the `select` is not necessary given that we are getting all the columns from the table. so you can leave it as: `await UserModel.query()` and it should work the same way.

2023-10-16 23:28 UTC, Ralexs0096 commented on src/routes/users/fetchAllUsers.ts
> +    }
nitpick: 

`
if(users.length === 0){
return reply.status(404).send({
        error: {
          code: "unknown",
          message: "No users found.",
        },
      });
}

reply.status(200).send(users);
`

2023-11-01 23:27 UTC, Ralexs0096 commented on src/routes/users/fetchAllUsers.ts
> +    );
since we are fetching all columns we could simply use 
```js
const users = await UserModel.query()
```

2023-11-01 23:28 UTC, Ralexs0096 commented on src/routes/users/fetchAllUsers.ts
> +  Reply: User[] | { error: ErrorSchema };
Good catch!

2023-11-01 23:29 UTC, Ralexs0096 commented on src/routes/users/fetchAllUsers.ts
> +    const users = await UserModel.query().select("firstName", "lastName","areaId");
❗ this suggestion was not applied

2023-11-09 04:19 UTC, AlvisonHunterArnuero requested changes

2023-11-09 04:19 UTC, AlvisonHunterArnuero commented on src/routes/users/fetchAllUsers.ts
> +      description: "An unknown error occurred when trying to fetch users.",
```suggestion
      description: "An unknown error occurred while attempting to retrieve users data.",
```

2023-11-10 01:42 UTC, merged

2023-11-10 03:22 UTC, Ralexs0096 commented on src/routes/users/fetchAllUsers.ts
> +      propiesties: UserSchema,
Properties* you will fix this in a new PR @leandro0day